# Generated by Django 5.0 on 2025-03-11 21:08

import django.db.models.deletion
import imagekit.models.fields
import mobile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the post.', max_length=255)),
                ('description', models.TextField(help_text='Enter the content or description of the post.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the post was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the post was last updated.')),
                ('category', models.ForeignKey(help_text='Select the category for the post.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='base.category')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=mobile.models.post_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the image was uploaded.')),
                ('post', models.ForeignKey(help_text='The post to which this image is associated.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mobile.post')),
            ],
        ),
    ]
