# Generated by Django 5.0 on 2025-04-13 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='The content of the message.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the message was last updated.')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the message has been read.')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when the message was marked as read.', null=True)),
                ('receiver', models.ForeignKey(help_text='User who receives the message.', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sends the message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
