# Generated by Django 5.0 on 2025-03-12 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_postlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='The content of the comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time when the comment was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The time when the comment was last updated.')),
                ('post', models.ForeignKey(help_text='The post that this comment is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mobile.post')),
                ('user', models.ForeignKey(help_text='The user who made the comment.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
