# Generated by Django 5.0 on 2025-03-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the category.', max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, help_text='Automatically generated from the category name.', max_length=255, unique=True)),
            ],
        ),
    ]
